### ISSUE TITLE
ADNKit.framework/Headers missing ANKClient+ANKStreamMarker.h

### ISSUE THREAD

**Issue by subpop** [joeldev/ADNKit#37]
When using the precompiled framework, a new project throws an error, missing ANKClient+ANKStreamMarker.h. Copying it from the ADNKit folder into the framework works around.

**Comment by joeldev** [comment]
I recommend embedding the project itself and not using the precompiled framework. That will be going away entirely very soon.

**Comment by subpop** [comment]
Yea, I switched to embedding the project & building locally. The @executable_path stuff isn't worth the trouble.

**Comment by joeldev** [comment]
Well, I was more referring to setting up ADNKit as a build dependency, but embedding the source itself works too I suppose.

**Comment by subpop** [comment]
No that's what I did: "Drag ADNKit.xcodeproj into Xcode".
