### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by joeldev** [joeldev/ADNKit#4]
Tried to do this, failed miserably in header search path hell. Cocoapods doesn't seem great at handling a project with two targets that have different platforms. It always has a 'default target', which seemed to do nothing but cause tons of problems. So someone else can tackle this, or I'll do it later on a branch.

**Comment by ashfurrow** [comment]
I can take a look tonight – I've got experience writing podspecs.

**Comment by ashfurrow** [comment]
Oh my god there are tags – _thank you_.

**Comment by ashfurrow** [comment]
Might have to solve Issue #5 in order to do this, since CocoaPods won't install AFNetworking into a specific directory (as the header files are expecting).
