### ISSUE TITLE
Dot for ADN uses ADNKit

### ISSUE THREAD

**Issue by ghost** [joeldev/ADNKit#46]
Dot for ADN uses ADNKit. It is being developed by @nerd (me) and @amc, and is not available at this time. If you could add it to the list, that would be great.

Thanks!

**Comment by AMC** [comment]
There is some confusion on the @amc username. @amc at Alphas is who they meant-- Anthony Castelli, not @amc at GitHub which is a totally different person who is not involved in this project.

**Comment by ghost** [comment]
Yeah, sorry about that.
