### ISSUE TITLE
URLForSize not working

### ISSUE THREAD

**Issue by ghost** [joeldev/ADNKit#54]
The URLForSize method doesn't work if there are already some query arguments for the URL.
I corrected it to the following:

```
- (NSURL *)URLForSize:(CGSize)size {
    NSURL *URL = self.URL;

    if (size.width > 0 || size.height > 0) {

        NSString *queryExtension = (URL.query && URL.query.length) ? @"&" : @"?";
        NSMutableString *s = [NSMutableString stringWithFormat:@"%@%@", URL.absoluteString, queryExtension];

        if (size.width > 0) {
            [s appendFormat:@"w=%u", (unsigned int)size.width];
        }

        if (size.height > 0) {
            [s appendFormat:@"&h=%u", (unsigned int)size.height];
        }

        URL = [NSURL URLWithString:s];
    }

    return URL;
}
```

This works for me. Feel free to improve the code!

**Comment by kolinkrewinkel** [comment]
I'll give it a test later and put it in master, unless you submit a pull request (which would be awesome.) It actually raises awareness to a broader issue (which is that parameters with URLs are handled ineffectively and inconsistently when it comes to mutation on iOS and subsequently in ADNKit.)

**Comment by ffried** [comment]
Okay. I'll submit a pull request later. Just need to checkout the repo first (I integrated ADNKit with cocoapods).
